### ISSUE TITLE
Integrate automatically version conflict resolution, and allow excludes

### ISSUE THREAD

**Issue by jtrs** [cubbles/cubx-dependency-resolver#4]
**Tasks:**
- [x] add parameter `--excludes [listOfExcludes]` or `-e [listOfExcludes]`. Where `listOfExcludes` is JSON string with list of excludes (like in RTE) or a relative path to a JSON file.
- [x] add parameter `--acr` to enable Automatic Conflict Resolution (if parameter is given). If `--acr` is set then parameter `--type` needs to have value `list` (default value)
- [x] Release new version

**Comment by edwingamboa** [comment]
@jtrs should `--acr` parameter work only for type 'list'. Or you mean that when no type is provided 'list' should be set as default (as it works currently)?

**Comment by pwrinc** [comment]
The `--acr` parameter should work with all values for `--type` except `raw`. If no value is provided for `--type` then use default value `list`
